version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sheet_app_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/credentials.json:/usr/src/app/credentials.json:ro
      - ./backend/data:/usr/src/app/data

  frontend:
    build: ./frontend
    container_name: sheet_app_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
