services:
  backend:
    build: ./backend
    container_name: web_app_be
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/credentials.json:/usr/src/app/credentials.json:ro
      - ./backend/data:/usr/src/app/data
      - ./backend/src:/usr/src/app/src

  frontend:
    build: ./frontend
    container_name: web_app_fe
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
